---
name: New Release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Build
        run: make build-all VERSION=${{ github.event.release.tag_name }}

      - name: Upload
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_BUCKET_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_BUCKET_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          docker run -v ./bin:/build \
            -e "MC_HOST_bucket=https://${S3_ACCESS_KEY}:${S3_SECRET_KEY}@${S3_ENDPOINT}" \
            minio/mc cp -r /build/ bucket/${S3_BUCKET}/
  homebrew:
    needs: publish
    name: Bump Homebrew formula
    runs-on: ubuntu-24.04
    steps:
      - uses: mislav/bump-homebrew-formula-action@56a283fa15557e9abaa4bdb63b8212abc68e655c
        with:
          formula-name: infrahub-backup
          homebrew-tap: opsmill/homebrew-tap
          commit-message: "{{formulaName}} {{version}}"
        env:
          COMMITTER_TOKEN: ${{ secrets.GH_INFRAHUB_BOT_TOKEN }}
